# 게임에서 사용되는 아이템 정보를 담은 테이블 => ITEM_INFO
# 아이템 관계를 나타낸 테이블 => ITEM_TREE
# WHERE 희귀도가 RARE
# ORDER BY 아이템 ID를 기준으로 내림차순 정렬

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T ON T.ITEM_ID=I.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = "RARE")
ORDER BY I.ITEM_ID DESC