# 서점에서 판매중인 도서들의 도서 정보 => BOOK
# SELECT => 도서 ID, 출판일
# WHERE => 2021년에 출판 , 인문 카테고리
# ORDER BY => 출판일을 기준으로 오름차순

SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE,"%Y-%m-%d") AS PUBLISHED_DATE
FROM BOOK
WHERE PUBLISHED_DATE BETWEEN "2021-01-01" AND "2021-12-31" AND CATEGORY = "인문"
ORDER BY PUBLISHED_DATE