# USED_GOODS_BOARD => 중고거래 게시판 정보
# USED_GOODS_REPLY => 중고거래 게시판 첨부파일 정보
# 댓글 작성일 기준으로 오름차순, 만약 같다면 게시글 제목을 기준으로 오름차순
# 2022년 작성된 것을 고르는 것이 문제

SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_REPLY AS R ON R.BOARD_ID=B.BOARD_ID
WHERE B.CREATED_DATE >="2022-10-01" AND B.CREATED_DATE < "2022-11-01"
ORDER BY R.CREATED_DATE ASC, B.TITLE

